stages:
- build
- deploy

rust-latest:
  stage: build
  image: rust:latest
  script:
  - cargo build --verbose
  - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
  - cargo build --verbose
  - cargo test --verbose
  allow_failure: true

flathost:
  stage: deploy
  image: rust:latest
  script:
  - cargo doc --no-deps --verbose
  - wget http://public.ekranos.me/flathost/flathost-client
  - chmod +x flathost-client
  - ./flathost-client -u $FLATHOST_URL -d target/doc -n nagiosplugin -t $FLATHOST_TOKEN
  allow_failure: true

pages:
  image: rust:latest
  stage: deploy
  script:
  - cargo doc --verbose
  - mv target/doc public
  dependencies:
  - rust-latest
  artifacts:
    paths:
    - public
  only:
  - master