stages:
- build
- deploy

rust-latest:
  stage: build
  image: rust:latest
  script:
  - cargo build --verbose
  - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
  - cargo build --verbose
  - cargo test --verbose
  allow_failure: true

pages:
  image: rust:latest
  stage: deploy
  script:
  - cargo doc --verbose
  - mv target/doc public
  dependencies:
  - rust-latest
  artifacts:
    paths:
    - public
  only:
  - master