language: rust
rust:
- stable
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master